-- USER SQL
CREATE USER "Event" IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "DBA" TO "Event" ;
GRANT "CONNECT" TO "Event" ;
GRANT "RESOURCE" TO "Event" ;

-- SYSTEM PRIVILEGES

