drop table member;
drop table mypage;
CREATE TABLE MEMBER 
(
  NAME VARCHAR2(20) NOT NULL 
, TEL VARCHAR2 (20) NOT NULL 
, ID VARCHAR2(20) NOT NULL 
, PW VARCHAR2(20) NOT NULL 
);
CREATE TABLE MYPAGE 
(
  NAME VARCHAR2(20 BYTE) NOT NULL 
, TEL VARCHAR2(20 BYTE) NOT NULL 
, POINT NUMBER NOT NULL 
, COUPON1 VARCHAR2(20 BYTE) 
, COUPON2 VARCHAR2(20 BYTE) 
, COUPON3 VARCHAR2(20 BYTE) 
) ;
